// components/info/index.vue
<template>
  <Grid align-items="center" justify="space-between" :class="$style.info">
    <img src="~/assets/info.png" :class="$style.phone" />
    <Grid direction="column" :class="$style.info">
      <p :class="[$style.text, $style.text_h1]">Fliness Messenger</p>
      <p :class="[$style.text, $style.text_h2]">
        New Ways to Navigate
        <br />
        Your Messenger
      </p>
      <p :class="[$style.text, $style.text_h3]">
        All of your favorite features,
        <br />
        organized to make it faster <br />
        to find what you want
      </p>
    </Grid>
  </Grid>
</template>

<script lang="ts">
import Vue from 'vue';
import Grid from '~/ui/grid/index.vue';
export default Vue.extend({
  components: { Grid },
});
</script>

<style lang="scss" module src="./index.module.scss"></style>

// src/components/info/info.tsx
import React from 'react';
import Grid from '@material-ui/core/Grid';
import classes from '@components/info/info.module.scss';
import classNames from 'classnames';

export const Info: React.FC = () => {
	return (
		<Grid
			container
			direction='row'
			alignItems='center'
			justify='space-between'
			className={classes.info}
		>
			<img src={'./info.png'} className={classes.phone}/>
			<Grid
				container
				direction='column' 
				className={classes.info}
			>
				<p className={classNames(classes.text, classes.text_h1)}>Fliness Messenger</p>
				<p className={classNames(classes.text, classes.text_h2)}>New Ways to Navigate<br/>Your Messenger</p>
				<p className={classNames(classes.text, classes.text_h3)}>All of your favorite features,<br/> organized to make it faster<br/> to find what you want</p>
			</Grid>
		</Grid>
	);
}

export default Info;
