// src/pages/sign-up/index.tsx
import React from 'react';
import useApollo from '@lib/use-apollo';
import Grid from '@material-ui/core/Grid';
import WaveIcon from '@public/wave.svg';
import SignupForm from '@components/forms/sign-up/sign-up';
import classes from './index.module.scss';
import Info from '@components/info/info';

export const Signup: React.FC = () => {
  return (
    <Grid
      container
      direction="column"
      justify="center"
      alignItems="center"
      className={classes.page}
    >
      <WaveIcon className={classes.page__background} />
      <Grid
        container
        direction="row"
        justify="space-between"
        alignItems="center"
        className={classes.container}
      >
        <Info />
        <SignupForm />
      </Grid>
    </Grid>
  );
};

export default useApollo(Signup);

// pages/sign-up/index.vue
<script>
import Grid from '~/ui/grid/index.vue';
import Info from '~/components/info/index.vue';
import SignUpForm from '~/components/forms/auth/sign-up/index.vue';
import WaveIcon from '~/assets/wave.svg?inline';

export default {
  components: {
    'ui-grid': Grid,
    'info-field': Info,
    'sign-up-form': SignUpForm,
    'wave-icon': WaveIcon,
  },
  head() {
    return {
      title: 'Fliness Messenger - Sign Up',
    };
  },
};
</script>

<template>
  <ui-grid
    direction="column"
    align-items="center"
    justify="center"
    :class="$style.page"
  >
    <wave-icon :class="$style.page__background" />
    <ui-grid
      justify="space-between"
      align-items="center"
      :class="$style.container"
    >
      <info-field />
      <sign-up-form />
    </ui-grid>
  </ui-grid>
</template>

<style module lang="scss" src="./index.module.scss"></style>
