// ui/button/index.vue
<template>
  <button
    :class="[$style.btn, $style[`btn_${variant}`]]"
    @click="(e) => this.$emit('click', e)"
  >
    <slot></slot>
  </button>
</template>

<script lang="ts">
import Vue from 'vue';
export default Vue.extend({
  props: {
    variant: {
      type: String,
      required: true,
      validator(val) {
        return ['contained', 'outlined', 'text'].includes(val);
      },
    },
  },
});
</script>

<style lang="scss" module src="./index.module.scss"></style>

// src/ui/button/button.tsx
import React from 'react';
import classNames from 'classnames';
import classes from '@ui/button/button.module.scss';

export interface Props {
    className?: string
    children?: JSX.Element | JSX.Element[] | string
    onClick?: () => void
    variant?: 'contained' | 'outlined'
}

export const Button: React.FC<Props> = ({
    className = '',
    children,
    variant,
    onClick = () => {}
}: Props) => {
    return (
        <button 
            className={classNames(
                classes['btn'],
                variant === 'contained' ? classes['btn_contained'] : '',
                variant === 'outlined' ? classes['btn_outlined'] : '',
                className
            )}
            onClick={onClick}
        >
            {children}
        </button>
    );
};

export default Button;
