// components/side-bar/menu-item.vue
<template>
  <ui-button
    variant="text"
    :class="[$style.menu__item, { [$style.menu__item_active]: active }]"
  >
    <div :class="$style.item__icon">
      <slot></slot>
    </div>
  </ui-button>
</template>

<script lang="ts">
import Vue from 'vue';
import Button from '~/ui/button/index.vue';

export default Vue.extend({
  components: {
    'ui-button': Button,
  },
  props: {
    active: {
      type: Boolean,
      default: false,
    },
  },
});
</script>

<style lang="scss" module src="./index.module.scss"></style>

// src/components/side-bar/menu-item/menu-item.tsx
import React from 'react';
import Grid from '@ui/grid/grid';
import Button from '@ui/button/button';
import classNames from 'classnames';
import classes from '@components/side-bar/side-bar.module.scss';

export interface Props {
  active?: boolean;
  Icon: React.FC<any>;
  onClick?: () => void;
  className?: string;
}

export const MenuItem: React.FC<Props> = ({
  active = false,
  Icon,
  onClick = () => {},
  className,
}: Props) => {
  return (
    <Grid>
      <Button
        className={classNames(classes['menu__item'], className, {
          [classes['menu__item_active']]: active,
        })}
        onClick={onClick}
      >
        <Icon className={classes['item__icon']} />
      </Button>
    </Grid>
  );
};

export default MenuItem;
