// components/list-bar/index.vue
<template>
  <ui-grid direction="column" :class="$style.list_bar">
    <ui-grid direction="column" :class="$style.list_bar__header">
      <h1 :class="$style.list_bar__title">{{ title }}</h1>
      <search />
      <ui-grid
        align-ttems="center"
        justify="space-between"
        :class="$style.list_bar__btns"
      >
        <create-dialog-modal />
      </ui-grid>
    </ui-grid>
    <ui-grid direction="column" :class="$style.list">
      <template v-for="chat in chats">
        <ui-grid
          v-if="!getUser(chat.id)"
          :key="chat.id"
          :class="[$style.list_item, $style.list_item_skeleton]"
        >
          <ui-skeleton width="100%" height="60px" radius="4px"></ui-skeleton>
        </ui-grid>
        <list-item
          v-else
          :key="chat.id"
          :username="getUser(chat.id).name"
          :avatarURL="getUser(chat.id).avatarURL"
          :title="getUser(chat.id).name"
          :active="currentChatId === chat.id"
          description=""
          time=""
          messages=""
          @click="handleListItemClick(chat.id)"
        />
      </template>
    </ui-grid>

    <side-bar-horizontal v-if="showHorizontalSideBar"></side-bar-horizontal>
  </ui-grid>
</template>

<script lang="ts">
import Vue from 'vue';
import { mapState } from 'vuex';
import ListItem from './list-item.vue';
import Grid from '~/ui/grid/index.vue';
import Skeleton from '~/ui/skeleton/index.vue';
import Search from '~/components/search/index.vue';
import SideBarHorizontal from '~/components/side-bar/horizontal/index.vue';
import CreateDialogModal from '~/components/dialogs/create-dialog/index.vue';
import { MenuStateEnum } from '~/store/flex/types';
import { Actions, ChatTypesEnum } from '~/store/chats/types';

export default Vue.extend({
  components: {
    'ui-grid': Grid,
    'ui-skeleton': Skeleton,
    'list-item': ListItem,
    search: Search,
    'create-dialog-modal': CreateDialogModal,
    'side-bar-horizontal': SideBarHorizontal,
  },
  props: {
    title: {
      type: String,
      required: true,
    },
  },
  computed: {
    ...mapState({
      me: (state: any) => state.me,
      menuState: (state: any) => state.flex.menuState,
      chats: (state: any) => state.chats.all,
      members: (state: any) => state.members.all,
      users: (state: any) => state.users.all,
      currentChatId: (state: any) => state.chats.currentChatId,
    }),
    showHorizontalSideBar() {
      return this.menuState === MenuStateEnum.MOVING_OVER_WITH_SIDE_BAR_ACTIVE;
    },
    companions() {
      return this.members.filter((member) => member.userId !== this.me.id);
    },
  },
  async mounted() {
    await this.$store.dispatch(Actions.GET_CHATS, {
      type: ChatTypesEnum.DIALOG,
    });
  },
  methods: {
    async handleListItemClick(chatId: string) {
      const payload: Actions.SetCurrentChatPayload = {
        chatId,
      };
      await this.$store.dispatch(Actions.SET_CURRENT_CHAT, payload);

      this.$router.push(`/dialogs/${chatId}`);
    },
    getUser(chatId: string) {
      // @ts-ignore
      const member = this.companions.find((member) => member.chatId === chatId);

      if (!member) return;

      return this.users.find((users) => users.id === member.userId);
    },
  },
});
</script>

<style lang="scss" module src="./index.module.scss"></style>

// src/components/list-bar/list-bar.tsx
import React from 'react';
import Grid from '@ui/grid/grid';
import List from '@ui/list/list';
import Search from '@components/search/search';
import CreateDialog from '@components/dialogs/create-dialog/create-dialog';
import classes from '@components/list-bar/list-bar.module.scss';
import classNames from 'classnames';
import { MenuStateEnum } from '@store/menu';
import { gql, useQuery } from '@apollo/client';
import SideBar from '@components/side-bar/side-bar';
import { GET_DIALOGS, GET_LOCAL_STATE } from './list-bar.graphql';
import Skeleton from '@ui/skeleton/skeleton';
import { currentChatVar } from '@store/chats';
import { useRouter } from 'next/router';

export interface ItemType {
  id: string;
  title: string;
  desc: string;
  time: string;
  messages: number;
  avatarURL: string;
  active: boolean;
}

export interface Props {
  title: string;
  children?: JSX.Element[];
}

export const ListBar: React.FC<Props> = ({ title }) => {
  const router = useRouter();
  const {
    data: {
      localState: { menuState, currentChat: currentChat },
    },
  } = useQuery(GET_LOCAL_STATE);
  const { error, data, loading } = useQuery(GET_DIALOGS, {
    variables: {
      filter: {
        field: {
          name: 'TYPE_NAME',
          op: 'EQUALS',
          val: 'DIALOG',
        },
      },
    },
  });

  const dialogs = [];

  if (!loading && !error) {
    const {
      me: {
        id: userId,
        chats: { edges: chats },
      },
    } = data;
    dialogs.push(
      ...chats.map(
        ({
          node: {
            id,
            members: { edges: members },
          },
        }) => {
          const {
            node: { user: interlocutor },
          } = members.find(({ node: { user } }) => user.id !== userId);
          return {
            id,
            title: interlocutor.name,
            desc: '',
            time: '',
            messages: 0,
            avatarURL: interlocutor.avatarURL,
            active: currentChat === id,
          };
        }
      )
    );
  } else if (!dialogs.length) {
    for (let i = 0; i > 5; ++i) dialogs.push({ id: i });
  }

  return (
    <Grid
      direction="column"
      className={classNames(
        classes['list-bar'],
        {
          [classes['list-bar_show']]: menuState === MenuStateEnum.MOVING_ACTIVE,
        },
        {
          [classes['list-bar_hidden']]:
            menuState === MenuStateEnum.MOVING_DEACTIVE,
        }
      )}
    >
      <Grid direction="column" className={classes['list-bar__header']}>
        <h1 className={classes['list-bar__title']}>{title}</h1>
        <Search />
        <Grid
          alignItems="center"
          justify="space-between"
          direction="row"
          className={classes['list-bar__btns']}
        >
          <CreateDialog />
        </Grid>
      </Grid>
      {loading || error ? (
        <List items={dialogs} className={classes['list']}>
          {({ id }) => (
            <Grid
              key={id}
              className={classNames(
                classes['list-item'],
                classes['list-item_skeleton']
              )}
            >
              <Skeleton width="100%" height="60px" />
            </Grid>
          )}
        </List>
      ) : (
        <List items={dialogs} className={classes['list']}>
          {({
            id,
            title,
            desc,
            time,
            messages,
            active,
            avatarURL,
          }: ItemType) => (
            <Grid
              key={id}
              alignItems="center"
              direction="row"
              wrap="nowrap"
              justify="space-between"
              className={classNames(classes['list-item'], {
                [classes['list-item_active']]: active,
              })}
              onClick={() => {
                currentChatVar(id);
                router.push(`/dialogs/${id}`);
              }}
            >
              <Grid
                alignItems="center"
                justify="space-between"
                className={classes['list-item__header']}
              >
                <div className={classes['list-item__avatar']}>
                  <img
                    className={classes['list-item__image']}
                    src={avatarURL}
                    alt=""
                  />
                  <span className={classes['list-item__status']}>
                    <span
                      className={classes['list-item__online-status']}
                    ></span>
                  </span>
                </div>
                <Grid direction="column" className={classes['list-item__text']}>
                  <p className={classes['list-item__title']}>{title}</p>
                  {desc ? (
                    <p className={classes['list-item__desc']}>{desc}</p>
                  ) : null}
                </Grid>
              </Grid>
              <Grid direction="column" className={classes['list-item__info']}>
                {time ? (
                  <p className={classes['list-item__time']}>{time}</p>
                ) : null}
                {messages ? (
                  <p className={classes['list-item__nums']}>
                    <span>{messages}</span>
                  </p>
                ) : null}
              </Grid>
            </Grid>
          )}
        </List>
      )}
      {menuState === MenuStateEnum.MOVING_ON_TOP_WITH_SIDE_BAR_ACTIVE ? (
        <SideBar.Horizontal />
      ) : null}
    </Grid>
  );
};

export default ListBar;
