// components/list-bar/skeleton.vue
<template>
  <ui-grid :class="$style.list" direction="column">
    <ui-grid
      v-for="i in 10"
      :key="i"
      :class="[$style.list_item, $style.list_item_skeleton]"
    >
      <ui-skeleton width="100%" height="60px" radius="4px"></ui-skeleton>
    </ui-grid>
  </ui-grid>
</template>

<script lang="ts">
import Vue from 'vue';
import Grid from '~/ui/grid/index.vue';
import Skeleton from '~/ui/skeleton/index.vue';

export default Vue.extend({
  components: {
    'ui-grid': Grid,
    'ui-skeleton': Skeleton,
  },
});
</script>

<style lang="scss" module src="./index.module.scss"></style>

// src/components/list-bar/skeleton.tsx
import { Skeleton } from '@ui/ui';
import React from 'react';
import Grid from '@ui/grid/grid';
import List from '@ui/list/list';
import classes from '@components/list-bar/list-bar.module.scss';
import classNames from 'classnames';

export const LBSkeleton: React.FC = () => {
  const items = [];

  for (let i = 0; i < 8; ++i) items.push({ id: i });

  return (
    <List items={items} className={classes['list']}>
      {({ id }) => (
        <Grid
          key={id}
          className={classNames(
            classes['list-item'],
            classes['list-item_skeleton']
          )}
        >
          <Skeleton width="100%" height="60px" />
        </Grid>
      )}
    </List>
  );
};

export default LBSkeleton;
