// src/components/forms/sign-in/sign-in.tsx
import React, { useRef, useState } from 'react';
import { useMutation } from '@apollo/client';
import { useRouter } from 'next/router';
import Grid from '@material-ui/core/Grid';
import Typography from '@material-ui/core/Typography';
import classes from './sign-in.module.scss';
import LogoIcon from '@public/logo.svg';
import Button from '@material-ui/core/Button';
import EmailIcon from '@public/email.svg';
import UnlockIcon from '@public/unlock.svg';
import { tokenVar } from '@store/auth';
import { SIGN_IN } from './sign-in.graphql';
import Padlock from '@public/padlock.svg';
import Link from 'next/link';

export const SinInForm: React.FC = () => {
  const emailField = useRef<HTMLInputElement | null>(null);
  const passwordField = useRef<HTMLInputElement | null>(null);

  const [signIn] = useMutation(SIGN_IN);
  const [lock, setLock] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);
  const router = useRouter();

  async function handleButtonClick() {
    const email = emailField.current.value;
    const password = passwordField.current.value;

    setLock(true);

    signIn({
      variables: {
        payload: {
          email,
          password,
        },
      },
      context: {
        withoutTokens: true,
      },
    })
      .then(({ data }) => {
        tokenVar(data.auth.signIn.accessToken);
        setError(null);
        router.push('/dialogs');
      })
      .catch(e => {
        if (e.message === `The user was not found with the email: ${email}`)
          setError('Invalid email or password');
        else console.error(e);
      })
      .finally(() => setLock(false));
  }

  return (
    <Grid
      container
      direction="column"
      justify="center"
      alignItems="center"
      className={classes.form__layout}
    >
      <LogoIcon className={classes.form__icon} />
      <Typography className={classes.form__title}>Sign in</Typography>
      <Typography className={classes.form__description}>
        to get started
      </Typography>

      <form
        className={classes.inputs_layout}
        onSubmit={handleButtonClick.bind(this)}
      >
        {error ? (
          <div className={classes.form__error_msg}>
            <Padlock className={classes.error_msg__icon} />
            <p>{error}</p>
          </div>
        ) : null}

        <div className={classes.form__input}>
          <EmailIcon className={classes.input__icon} />
          <input
            type="text"
            className={classes.input__shape}
            placeholder={'Email address or phone number'}
            ref={emailField}
          />
        </div>

        <div className={classes.form__input}>
          <UnlockIcon className={classes.input__icon} />
          <input
            type="password"
            className={classes.input__shape}
            placeholder={'Password'}
            ref={passwordField}
          />
        </div>
      </form>

      <div className={classes.form__button_layout}>
        <Button
          className={classes.form__button}
          variant="contained"
          onClick={handleButtonClick.bind(this)}
          disableElevation
          disabled={lock}
        >
          Continue
        </Button>
      </div>

      <Link href={'/sign-up'}>
        <Typography className={classes.form__link}>or sign up</Typography>
      </Link>
    </Grid>
  );
};

export default SinInForm;

// components/forms/auth/sign-in/index.vue
<script>
import Field from '../field/index.vue';
import ErrorField from '../error-field/index.vue';
import Grid from '~/ui/grid/index.vue';
import Button from '~/ui/button/index.vue';
import LogoIcon from '~/assets/logo.svg?inline';
import UnlockIcon from '~/assets/unlock.svg?inline';
import EmailIcon from '~/assets/email.svg?inline';
import * as AuthActions from '~/store/auth/actions';

export default {
  components: {
    'ui-grid': Grid,
    'ui-button': Button,
    'logo-icon': LogoIcon,
    'form-field': Field,
    'form-error-field': ErrorField,
    'unlock-icon': UnlockIcon,
    'email-icon': EmailIcon,
  },
  data() {
    return {
      email: null,
      password: null,
      error: null,
      loading: false,
    };
  },
  methods: {
    handleFieldInput(type, value) {
      switch (type) {
        case 'email':
          this.email = value;
          break;
        case 'password':
          this.password = value;
          break;
      }
    },
    async handleFormSubmit() {
      this.loading = true;

      await this.$store
        .dispatch(AuthActions.SIGN_IN, {
          email: this.email,
          password: this.password,
        })
        .then(() => {
          this.$router.push('/dialogs');
        })
        .catch(() => {
          this.error = 'The email or password is incorrect';
        })
        .finally(() => (this.loading = false));
    },
  },
};
</script>

<template>
  <ui-grid direction="column" align-items="center" :class="$style.form__layout">
    <logo-icon :class="$style.form__icon" />
    <p :class="$style.form__title">Sign in</p>
    <p :class="$style.form__description">to get started</p>
    <form :class="$style.inputs_layout" @submit.prevent="handleFormSubmit">
      <form-error-field v-if="error" :text="error"></form-error-field>
      <form-field
        type="text"
        placeholder="Email address or phone number"
        @input="(value) => handleFieldInput('email', value)"
      >
        <template #icon>
          <email-icon />
        </template>
      </form-field>
      <form-field
        type="password"
        placeholder="Password"
        @input="(value) => handleFieldInput('password', value)"
      >
        <template #icon>
          <unlock-icon />
        </template>
      </form-field>
      <div :class="$style.form__button_layout">
        <ui-button
          :class="$style.form__button"
          variant="contained"
          :disabled="loading"
        >
          Continue
        </ui-button>
      </div>
      <div :class="$style.form__link">
        <NuxtLink to="/sign-up"> or sign up </NuxtLink>
      </div>
    </form>
  </ui-grid>
</template>

<style lang="scss" module src="../index.module.scss"></style>
