// src/ui/skeleton/skeleton.tsx
import React from 'react';
import classNames from 'classnames';
import classes from '@ui/skeleton/skeleton.module.scss';

export interface Props {
  className?: string;
  width: string;
  height: string;
  radius?: string;
}

export const Skeleton: React.FC<Props> = ({
  className,
  width,
  height,
  radius = '4px',
}: Props) => {
  return (
    <span
      className={classNames(
        classes['skeleton'],
        classes['skeleton-pulse'],
        className
      )}
      style={{ width, height, borderRadius: radius }}
    ></span>
  );
};

export default Skeleton;

// ui/skeleton/index.vue
<template>
  <span
    :class="[$style.skeleton, $style.skeleton_pulse]"
    :style="{ width, height, borderRadius: radius }"
  >
  </span>
</template>

<script lang="ts">
import Vue from 'vue';

export default Vue.extend({
  props: {
    width: {
      type: String,
      required: true,
    },
    height: {
      type: String,
      required: true,
    },
    radius: {
      type: String,
      required: true,
    },
  },
});
</script>

<style lang="scss" module src="./index.module.scss"></style>
