// src/pages/sign-in/index.tsx
import { NextPage } from 'next';
import useApollo from '@lib/use-apollo';
import Grid from '@material-ui/core/Grid';
import WaveIcon from '@public/wave.svg';
import LoginForm from '@components/forms/sign-in/sign-in';
import classes from './index.module.scss';
import Info from '@components/info/info';

export const SignIn: NextPage = () => {
  return (
    <Grid
      container
      direction="column"
      justify="center"
      alignItems="center"
      className={classes.page}
    >
      <WaveIcon className={classes.page__background} />
      <Grid
        container
        direction="row"
        justify="space-between"
        alignItems="center"
        className={classes.container}
      >
        <Info />
        <LoginForm />
      </Grid>
    </Grid>
  );
};

export default useApollo(SignIn);

// pages/sign-in/index.vue
<template>
  <ui-grid
    direction="column"
    align-items="center"
    justify="center"
    :class="$style.page"
  >
    <wave-icon :class="$style.page__background" />
    <ui-grid
      justify="space-between"
      align-items="center"
      :class="$style.container"
    >
      <info-field />
      <sign-in-form />
    </ui-grid>
  </ui-grid>
</template>

<script lang="ts">
import Vue from 'vue';
import Grid from '~/ui/grid/index.vue';
import Info from '~/components/info/index.vue';
import SignInForm from '~/components/forms/auth/sign-in/index.vue';
// @ts-ignore
import WaveIcon from '~/assets/wave.svg?inline';

export default Vue.extend({
  components: {
    'ui-grid': Grid,
    'info-field': Info,
    'sign-in-form': SignInForm,
    'wave-icon': WaveIcon,
  },
  head() {
    return {
      title: 'Fliness Messenger - Sign In',
    };
  },
});
</script>

<style module lang="scss" src="./index.module.scss"></style>
