// components/search/index.vue
<template>
  <ui-grid align-items="center" :class="$style.search">
    <input type="text" placeholder="Search..." />
  </ui-grid>
</template>

<script lang="ts">
import Vue from 'vue';
import Grid from '~/ui/grid/index.vue';

export default Vue.extend({
  components: {
    'ui-grid': Grid,
  },
});
</script>

<style lang="scss" module src="./index.module.scss"></style>

// src/components/search/search.tsx
import React from 'react';
import classes from '@components/search/search.module.scss';
import Grid from '@ui/grid/grid';

export const Search: React.FC = () => {
    return (
        <Grid alignItems='center' className={classes['search']}>
            <input
                type='text'
                placeholder='Search...'
            />
        </Grid>
    );
};

export default Search;
