// components/info-bar/index.vue
<script>
import { mapActions, mapState } from 'vuex';
import AvatarIcon from './avatar-icon.vue';
import InfoButton from './btn.vue';
import UiGrid from '~/ui/grid/index';
import UiButton from '~/ui/button/index';
import UiSwitch from '~/ui/switch/index';
import CloseIcon from '~/assets/close.svg?inline';
import InfoIcon from '~/assets/information.svg?inline';
import BellIcon from '~/assets/bell.svg?inline';
import * as MenuInfoState from '~/store/flex/menu-info-state';
import * as FlexActions from '~/store/flex/actions';

export default {
  name: 'InfoBar',
  components: {
    UiGrid,
    UiButton,
    UiSwitch,
    CloseIcon,
    AvatarIcon,
    InfoIcon,
    BellIcon,
    InfoButton,
  },
  computed: {
    ...mapState({
      showInfoBar: (state) => state.flex.menuInfoState === MenuInfoState.ACTIVE,
    }),
  },
  methods: {
    ...mapActions({
      'changeMenuInfoState': FlexActions.CHANGE_MENU_INFO_STATE,
    }),
    handleInfoBarBtnClick() {
      this.changeMenuInfoState();
    },
  },
};
</script>

<template>
  <ui-grid
    align-items="center"
    direction="column"
    :class="['infobar', { 'infobar--active': showInfoBar }]"
  >
    <ui-grid align-items="center" class="infobar__header">
      <ui-grid align-items="center" justify="space-between">
        <p class="header__title">User Info</p>
        <ui-button
          variant="text"
          class="header__close-btn"
          @click="handleInfoBarBtnClick"
        >
          <close-icon></close-icon>
        </ui-button>
      </ui-grid>
    </ui-grid>
    <ui-grid align-items="center" class="infobar__chat-info">
      <avatar-icon username="Username" :url="null"></avatar-icon>
      <ui-grid
        direction="column"
        justify="space-between"
        class="chat-info__text"
      >
        <p class="chat-info__title">Username</p>
        <ui-grid align-items="center" class="chat-info__status">
          <p class="chat-info__status-title">Active Now</p>
          <span class="chat-info__status-icon"></span>
        </ui-grid>
      </ui-grid>
    </ui-grid>
    <ui-grid align-items="center" class="infobar__chat-info">
      <ui-grid justify="space-between">
        <info-icon class="chat-info__bio-icon"></info-icon>
        <ui-grid class="bio-link__bio-text" direction="column">
          <ui-grid class="bio-link__bio-parag" direction="column">
            <a class="bio-link__url">@user-link</a>
            <p class="bio-link__title">Link</p>
          </ui-grid>
          <ui-grid class="bio-link__bio-parag" direction="column">
            <a class="bio-link__text">@user-link</a>
            <p class="bio-link__title">Description</p>
          </ui-grid>
        </ui-grid>
      </ui-grid>
    </ui-grid>
    <ui-grid
      align-items="center"
      direction="column"
      class="infobar__chat-info infobar__notif"
    >
      <info-button class="btn__notif">
        <template #icon>
          <bell-icon class="btn__icon"></bell-icon>
        </template>
        <template #text> Notifications </template>
        <template #badge>
          <ui-switch></ui-switch>
        </template>
      </info-button>
      <!-- <info-button>
        <template #icon>
          <bell-icon class="btn__icon"></bell-icon>
        </template>
        <template #text> 0 photos </template>
      </info-button>
      <info-button>
        <template #icon>
          <bell-icon class="btn__icon"></bell-icon>
        </template>
        <template #text> 0 shared links </template>
      </info-button> -->
    </ui-grid>
    <ui-grid
      align-items="center"
      direction="column"
      class="infobar__chat-info infobar__bottom"
    >
      <info-button>
        <template #icon>
          <span class="btn__icon"></span>
        </template>
        <template #text> Delete Chat </template>
      </info-button>
    </ui-grid>
  </ui-grid>
</template>

<style lang="scss" src="./index.scss"></style>

// src/components/info-bar/info-bar.tsx
import Grid from '@/src/ui/grid/grid';
import React from 'react';
import classes from '@components/info-bar/info-bar.module.scss';
import CloseIcon from '@public/close.svg';
import InfoIcon from '@public/info.svg';
import BellIcon from '@public/bell.svg';
import ImageIcon from '@public/image.svg';
import LinkIcon from '@public/link.svg';
import ListIcon from '@public/list.svg';
import SliderIcon from '@public/slider.svg';
import { AvatarIcon } from '@components/chat-bar/avatar-icon';
import { Button } from '@/src/ui/ui';

export interface Props {
    title: string;
    avatarURL: string;
  }

export const InfoBar: React.FC<Props> = ({ title, avatarURL }: Props) => {
    return (
        <Grid direction="column" className={classes['info-bar']}>
            <Grid direction="row" className={classes['info-bar__header']}>
                <h1 className={classes['info-bar__header-title']}>User Info</h1>
                <Button className={classes['info-bar__header-button']}><CloseIcon className={classes['info-bar__header-close-icon']} /></Button>
            </Grid>

            <Grid alignItems="center" className={classes['info-bar__avatar']}>
                <Grid className={classes['info-bar__avatar-grid']}><AvatarIcon username={title} url={avatarURL}></AvatarIcon></Grid>
                <Grid direction="column" className={classes['info-bar__text']}>
                    <p className={classes['info-bar__title']}>{title}</p>
                    <Grid alignItems="center">
                        <p className={classes['info-bar__status']}>Active Now</p>
                        <span className={classes['info-bar__status-icon']}></span>
                    </Grid>
                </Grid>
            </Grid>
            
            <Grid direction="column" className={classes['info-bar__info']}>
                <Grid direction="row">
                    <InfoIcon className={classes['info-bar__info-icon']}/>
                    <p className={classes['info-bar__info-bio-click']}>Some biography</p>
                </Grid>
                <p className={classes['info-bar__info-bio-text']}>Bio</p>
                <p className={classes['info-bar__info-user-name']}>@anna-banu</p>
                <p className={classes['info-bar__info-user-text']}>Username</p>
            </Grid>

            <Grid direction="row" className={classes['info-bar__notif']}>
                <BellIcon className={classes['info-bar__notif-bell-icon']}/>
                <p className={classes['info-bar__notif-text']}>Notifications</p>
                <SliderIcon className={classes['info-bar__notif-slider-icon']}/>
            </Grid>

            <Grid direction="column" className={classes['info-bar__files']}>
                <Grid direction="row" className={classes['info-bar__files-photo-grid']}>
                    <Button className={classes['info-bar__files-button']}><ImageIcon className={classes['info-bar__files-image-icon']}/>
                    <p className={classes['info-bar__files-image-text']}>52 photos</p></Button>
                </Grid>
                <Grid direction="row" className={classes['info-bar__files-links-grid']}>
                    <Button className={classes['info-bar__files-button']}><LinkIcon className={classes['info-bar__files-link-icon']}/>
                    <p className={classes['info-bar__files-link-text']}>112 shared links</p></Button>
                </Grid>
            </Grid>

            <Grid direction="column" className={classes['info-bar__function']}>
                <Grid direction="row" className={classes['info-bar__function-grid']}>
                    <Button className={classes['info-bar__function-button']}><ListIcon className={classes['info-bar__function-list-icon']}/>
                    <p className={classes['info-bar__function-clear-history']}>Clear history</p></Button>
                </Grid>
                <Button className={classes['info-bar__function-button']}><p className={classes['info-bar__function-delete-chat']}>Delete chat</p></Button>
                <Button className={classes['info-bar__function-button']}><p className={classes['info-bar__function-block-user']}>Block user</p></Button>
            </Grid>
        </Grid>
    );
};

export default InfoBar;
