// ui/grid/index.vue
<template>
  <div
    :class="{
      [$style.grid]: true,
      [$style[`grid_dir-${direction}`]]: direction,
      [$style[`grid_justify-${justify}`]]: justify,
      [$style[`grid_align-${alignItems}`]]: alignItems,
    }"
    @click="handleClick"
  >
    <slot></slot>
  </div>
</template>

<script lang="ts">
import Vue from 'vue';

export default Vue.extend({
  props: {
    justify: {
      type: String,
      default: 'flex-start',
      validator(val) {
        return [
          'center',
          'start',
          'center',
          'end',
          'flex-start',
          'flex-end',
          'space-between',
          'space-around',
        ].includes(val);
      },
    },
    alignItems: {
      type: String,
      default: 'flex-start',
      validator(val) {
        return [
          'center',
          'start',
          'center',
          'end',
          'flex-start',
          'flex-end',
          'space-between',
          'space-around',
        ].includes(val);
      },
    },
    wrap: {
      type: String,
      default: 'nowrap',
      validator(val) {
        return ['nowrap', 'wrap', 'wrap-reverse'].includes(val);
      },
    },
    direction: {
      type: String,
      default: 'row',
      validator(val) {
        return ['row', 'column', 'row-reverse', 'column-revers'].includes(val);
      },
    },
  },
  methods: {
    handleClick(e) {
      this.$emit('click', e);
    },
  },
});
</script>

<style lang="scss" module src="./index.module.scss"></style>

// src/ui/grid/grid.tsx
import React from 'react';
import classNames from 'classnames';
import classes from '@ui/grid/grid.module.scss';

export interface Props {
    className?: string
    direction?: 'row' | 'column' | 'row-reverse' | 'column-revers'
    justify?: 'center' | 'start' | 'center' | 
        'end' | 'flex-start' | 'flex-end' | 
        'space-between' | 'space-around'
    alignItems?: 'center' | 'start' | 'center' | 
        'end' | 'flex-start' | 'flex-end' | 
        'space-between' | 'space-around'
    wrap?: 'nowrap' | 'wrap' | 'wrap-reverse'
    children?: JSX.Element | JSX.Element[] | string
}

export const Grid: React.FC<Props> = ({
    className = '',
    direction = 'row',
    justify = 'flex-start',
    alignItems = 'flex-start',
    children
}: Props) => {
    return (
        <div className={classNames(
            classes['grid'],
            classes[`grid_dir-${direction}`],
            classes[`grid_justify-${justify}`],
            classes[`grid_align-${alignItems}`],
            className
        )}>
            {children}
        </div>
    )
}

export default Grid;
