// components/forms/auth/sign-up/index.vue
<script>
import Field from '../field/index.vue';
import ErrorField from '../error-field/index.vue';
import Grid from '~/ui/grid/index.vue';
import Button from '~/ui/button/index.vue';
import LogoIcon from '~/assets/logo.svg?inline';
import UnlockIcon from '~/assets/unlock.svg?inline';
import EmailIcon from '~/assets/email.svg?inline';
import UserIcon from '~/assets/user.svg?inline';
import * as AuthActions from '~/store/auth/actions';

export default {
  components: {
    'ui-grid': Grid,
    'ui-button': Button,
    'logo-icon': LogoIcon,
    'form-field': Field,
    'form-error-field': ErrorField,
    'unlock-icon': UnlockIcon,
    'email-icon': EmailIcon,
    'user-icon': UserIcon,
  },
  data() {
    return {
      username: null,
      email: null,
      password: null,
      repeatPassword: null,
      error: null,
      loading: false,
    };
  },
  methods: {
    handleFieldInput(type, value) {
      switch (type) {
        case 'username':
          this.username = value;
          break;
        case 'email':
          this.email = value;
          break;
        case 'password':
          this.password = value;
          break;
        case 'repeat-password':
          this.repeatPassword = value;
          break;
      }
    },
    async handleFormSubmit() {
      if (this.password !== this.repeatPassword) {
        this.error = 'The passwords are not match';
        return;
      }

      this.loading = true;

      await this.$store
        .dispatch(AuthActions.SIGN_UP, {
          name: this.username,
          email: this.email,
          password: this.password,
        })
        .then(() => {
          this.$router.push('/dialogs');
        })
        .catch(() => {
          this.error = 'The email or password is incorrect';
        })
        .finally(() => (this.loading = false));
    },
  },
};
</script>

<template>
  <ui-grid direction="column" align-items="center" :class="$style.form__layout">
    <logo-icon :class="$style.form__icon" />
    <p :class="$style.form__title">Sign up</p>
    <p :class="$style.form__description">to get started</p>
    <form :class="$style.inputs_layout" @submit.prevent="handleFormSubmit">
      <form-error-field v-if="error" :text="error"></form-error-field>
      <form-field
        type="text"
        placeholder="Username"
        @input="(value) => handleFieldInput('username', value)"
      >
        <template #icon>
          <user-icon />
        </template>
      </form-field>
      <form-field
        type="text"
        placeholder="Email address or phone number"
        @input="(value) => handleFieldInput('email', value)"
      >
        <template #icon>
          <email-icon />
        </template>
      </form-field>
      <form-field
        type="password"
        placeholder="Password"
        @input="(value) => handleFieldInput('password', value)"
      >
        <template #icon>
          <unlock-icon />
        </template>
      </form-field>
      <form-field
        type="password"
        placeholder="Repeat password"
        @input="(value) => handleFieldInput('repeat-password', value)"
      >
        <template #icon>
          <unlock-icon />
        </template>
      </form-field>
      <div :class="$style.form__button_layout">
        <ui-button
          :class="$style.form__button"
          variant="contained"
          :disabled="loading"
        >
          Continue
        </ui-button>
      </div>
      <div :class="$style.form__link">
        <NuxtLink to="/sign-in"> or sign in </NuxtLink>
      </div>
    </form>
  </ui-grid>
</template>

<style lang="scss" module src="../index.module.scss"></style>

// src/components/forms/signup/signup.tsx
import React, { useRef, useState } from 'react';
import { useMutation } from '@apollo/client';
import { useRouter } from 'next/router';
import Grid from '@material-ui/core/Grid';
import Typography from '@material-ui/core/Typography'
import classes from './signup.module.scss';
import LogoIcon from '@public/logo.svg';
import Button from '@material-ui/core/Button';
import EmailIcon from '@public/email.svg';
import UserIcon from '@public/user.svg';
import UnlockIcon from '@public/unlock.svg';
import { tokenVar } from '@store/auth';
import { SIGN_UP } from '@components/forms/signup/signup.graphql';
import Padlock from '@public/padlock.svg';
import Link from "next/link";

export const SignUpForm: React.FC = () => {

	const userField = useRef(null);
	const emailField = useRef(null);
	const passwordField = useRef(null);
	const repeatField = useRef(null);

	const [signUp] = useMutation(SIGN_UP);
	const [lock, setLock] = useState(false);
	const [error, setError] = useState(null);
	const router = useRouter();

	async function handleButtonClick() {
		const name = userField.current.value;
		const email = emailField.current.value;
		const password = passwordField.current.value;
		const repeat = repeatField.current.value;

		setLock(true);

		if (password !== repeat) {
			setError('The passwords is not matches');
			setLock(false);
			return;
		}

		signUp({
			variables: {
				payload: {
					   name,
					email,
					   password
				}
			}
		})
		.then(({ data }) => {
			tokenVar(data.auth.register.accessToken);
			setError(null);
			router.push('/dialogs');
		})
		.catch(e => {
			if (e.message === `The user was not found with the email: ${email}`) 
				setError('Invalid email or password');
		})
		.finally(() => setLock(false));
	}

	return (
		<Grid
			container
			direction='column' 
			justify='center' 
			alignItems='center'
			className={classes.form__layout}
		>
			<LogoIcon className={classes.form__icon}/>
			<Typography className={classes.form__title}>Sign up</Typography>
			<Typography className={classes.form__description}>to get started</Typography>
            
			<form className={classes.inputs_layout} onSubmit={handleButtonClick.bind(this)}>

				{
					error ?
						<div className={classes.form__error_msg}>
							<Padlock className={classes.error_msg__icon}/>
							<p>{error}</p>
						</div>
						: null
				}

				<div className={classes.form__input}>
					<UserIcon className={classes.input__icon}/>
					<input 
						type='text' 
						className={classes.input__shape} 
						placeholder={'Username'} 
						ref={userField}
					/>
				</div>

				<div className={classes.form__input}>
					<EmailIcon className={classes.input__icon}/>
					<input 
						type='text' 
						className={classes.input__shape} 
						placeholder={'Email address or phone number'} 
						ref={emailField}
					/>
				</div>

				<div className={classes.form__input}>
					<UnlockIcon className={classes.input__icon}/>
					<input 
						type='password' 
						className={classes.input__shape} 
						placeholder={'Password'} 
						ref={passwordField}
					/>
				</div>

				<div className={classes.form__input}>
					<UnlockIcon className={classes.input__icon}/>
					<input 
						type='password' 
						className={classes.input__shape} 
						placeholder={'Repeat password'} 
						ref={repeatField}
					/>
				</div>

			</form>

			<div className={classes.form__button_layout}>
				<Button
					className={classes.form__button}
					variant="contained"
					onClick={handleButtonClick.bind(this)}
					disableElevation
					disabled={lock}
				>
                    Continue
				</Button>
			</div>

			<Link href={'/signin'}>
				<Typography className={classes.form__link}>or sign in</Typography>
			</Link>
            
		</Grid>
	);
}

export default SignUpForm;
