// pages/dialogs/index.vue
<template>
  <main-layout>
    <template #listbar>
      <list-bar title="Dialogs"></list-bar>
    </template>
    <template #content>
      <ui-grid
        direction="column"
        align-items="center"
        justify="center"
        :class="[$style.chat_messages, $style.chat_messages__plug]"
      >
        <ui-grid direction="column" align-items="center" :class="[$style.plug]">
          <dialogs-icon :class="[$style.plug__icon]"></dialogs-icon>
          <p :class="[$style.plug__title]">Please select a dialog</p>
          <p :class="[$style.plug__desc]">to start messaging</p>
        </ui-grid>
      </ui-grid>
    </template>
  </main-layout>
</template>

<script lang="ts">
import Vue from 'vue';
import Grid from '~/ui/grid/index.vue';
import ListBar from '~/components/list-bar/index.vue';
import MainLayout from '~/layouts/main.vue';
// @ts-ignore
import DialogsIcon from '~/assets/chat_bubble_outline.svg?inline';

export default Vue.extend({
  components: {
    'ui-grid': Grid,
    'list-bar': ListBar,
    'main-layout': MainLayout,
    'dialogs-icon': DialogsIcon,
  },
  middleware: ['auth'],
  head() {
    return {
      title: 'Fliness Messenger - Dialogs',
    };
  },
});
</script>

<style lang="scss" module src="./index.module.scss"></style>

// src/pages/dialogs/index.tsx
import { NextPage } from 'next';
import React from 'react';
import useApollo from '@lib/use-apollo';
import Error from 'next/error';
import { GET_USER } from '@pages/dialogs/index.graphql';
import ListBar from '@components/list-bar/list-bar';
import { PageTypeEnum, currentPageVar } from '@store/pages';
import SideBar from '@components/side-bar/vertical/side-bar';
import Grid from '@ui/grid/grid';
import DefaultLayout from '@components/layouts/default/defualt';
import classes from '@pages/dialogs/index.module.scss';
import classNames from 'classnames';
import DialogsIcon from '@public/chat_bubble_outline.svg';
import { currentChatVar } from '@store/chats';
import Request, { RequestResponse } from '@lib/request';

export interface Data {
  me: {
    name: string;
    avatarURL: string;
  };
}

export const DialogsPage: NextPage<RequestResponse<Data>> = ({
  error,
  statusCode,
  data,
}: RequestResponse<Data>) => {
  if (error) return <Error statusCode={statusCode} />;

  React.useEffect(() => {
    currentPageVar(PageTypeEnum.DIALOGS);
    currentChatVar(null);
  }, []);

  const {
    me: { name, avatarURL },
  } = data;

  return (
    <DefaultLayout
      username={name}
      avatarURL={avatarURL}
      sidebar={<SideBar />}
      listbar={<ListBar title={'Dialogs'} />}
    >
      <Grid
        direction="column"
        alignItems="center"
        justify="center"
        className={classNames(
          classes['chat-messages'],
          classes['chat-messages__plug']
        )}
      >
        <Grid
          direction="column"
          alignItems="center"
          className={classes['plug']}
        >
          <DialogsIcon className={classes['plug__icon']} />
          <p className={classes['plug__title']}>Please select a dialog</p>
          <p className={classes['plug__desc']}>to start messaging</p>
        </Grid>
      </Grid>
    </DefaultLayout>
  );
};

DialogsPage.getInitialProps = async ({ apolloClient }: any = {}) => {
  const getCurrentChatResponse = await Request.make(apolloClient, {
    query: GET_USER,
  });

  if (getCurrentChatResponse.error) return getCurrentChatResponse;

  return {
    statusCode: 200,
    data: getCurrentChatResponse.data,
  };
};

export default useApollo(DialogsPage);
