// components/chat-input/index.vue
<template>
  <ui-grid align-items="center" :class="$style.chat_input">
    <ui-button variant="text" :class="$style.chat_input__btn">
      <clip-icon :class="$style.btn__icon" />
    </ui-button>
    <ui-button variant="text" :class="$style.chat_input__btn">
      <camera-icon :class="$style.btn__icon" />
    </ui-button>
    <input
      type="text"
      :class="$style.chat_input__input"
      placeholder="Type your message"
    />
    <ui-button variant="text" :class="$style.chat_input__btn">
      <plane-icon :class="$style.btn__icon" />
    </ui-button>
  </ui-grid>
</template>

<script lang="ts">
import Vue from 'vue';
import Grid from '~/ui/grid/index.vue';
import Button from '~/ui/button/index.vue';
// @ts-ignore
import ClipIcon from '~/assets/paper-clip.svg?inline';
// @ts-ignore
import PlaneIcon from '~/assets/paper-plane.svg?inline';
// @ts-ignore
import CameraIcon from '~/assets/camera.svg?inline';

export default Vue.extend({
  components: {
    'ui-grid': Grid,
    'ui-button': Button,
    'clip-icon': ClipIcon,
    'plane-icon': PlaneIcon,
    'camera-icon': CameraIcon,
  },
});
</script>

<style lang="scss" module src="./index.module.scss"></style>

// src/components/chat-input/chat-input.tsx
import React from 'react';
import classes from '@components/chat-input/chat-input.module.scss';
import Grid from '@ui/grid/grid';
import Button from '@ui/button/button';
import ClipIcon from '@public/paper-clip.svg';
import PlaneIcon from '@public/paper-plane.svg';
import CameraIcon from '@public/camera.svg';

export interface Props {
  className?: string;
}

export const ChatInput: React.FC<Props> = ({ className }: Props) => {
  return (
    <Grid alignItems="center" className={classes['chat-input']}>
      <Button className={classes['chat-input__btn']}>
        <ClipIcon className={classes['btn__icon']} />
      </Button>
      <Button className={classes['chat-input__btn']}>
        <CameraIcon className={classes['btn__icon']} />
      </Button>
      <input
        type="text"
        className={classes['chat-input__input']}
        placeholder="Type your message"
      />
      <Button className={classes['chat-input__btn']}>
        <PlaneIcon className={classes['btn__icon']} />
      </Button>
    </Grid>
  );
};

export default ChatInput;
